### ISSUE TITLE
Issue during installation with PyQt5-5.15.10

### ISSUE THREAD

**Issue by cHJlaXpoZXI** [skelsec/evilrdp#2]
Hi !

Thank you for your tool ! I really want to try it but I face some issue during installation.

I tried with pipx and basic pip install and it hang on the same step : installing PyQT5. After some debug, It hangs because it ask for licensing.

```
  Installing collected packages: setuptools, packaging, sip, PyQt-builder
  Successfully installed PyQt-builder-1.15.4 packaging-23.2 setuptools-69.0.2 sip-6.8.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Querying qmake about your Qt installation...
  This is the GPL version of PyQt 5.15.10 (licensed under the GNU General Public License) for Python 3.11.7 on linux.

  Type 'L' to view the license.
  Type 'yes' to accept the terms of the license.
  Type 'no' to decline the terms of the license.
  ```
  
I cannot accept because I have no prompt at this time. I tried some workaround found on StackOverflow but no one worked.

OS : Debian 12 (Docker)
Arch : aarch64 (Host is mac M1)

I think is the aarch64 environment that cause issue. I tried to install PyQT6 but I ran an error :

```
Collecting PyQt6
  Using cached PyQt6-6.6.1.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/opt/tools/evilrdp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/tools/evilrdp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/tools/evilrdp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g30idv3r/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-g30idv3r/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-g30idv3r/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 603, in setup
          self.update(tool)
        File "/tmp/pip-install-fss90z0g/pyqt6_574102735a964f7b8553d0db6bd1dc1b/project.py", line 163, in update
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If you have any idea I take it :)

Best regards,

**Comment by cHJlaXpoZXI** [comment]
Okay so yeah I confirm that the issue come from the arch. I spin up an intel based VM and the installation was good.

I cannot launch the app but I think it's linked to the fact that I haven't any Graphical environment to bring up the GUI.

Regards,
